//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BADataEntity : NSObject
{
    _Bool _needCache;
    NSString *_urlString;
    id _parameters;
}

@property(nonatomic, getter=isNeedCache) _Bool needCache; // @synthesize needCache=_needCache;
@property(copy, nonatomic) id parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;

@end

